name: Ansible - Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint-ansible:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up direnv
        uses: andreygubarev/direnv-action@v1

      - name: Lint with ansible-lint
        run: |
          direnv allow
          direnv exec ansible-lint -v
